### ISSUE TITLE
Floating widgets break when dragged off screen in IE 10

### ISSUE THREAD

**Issue by roemhildtg** [cmv/cmv-app#379]
Hey there, I like the new addition of dragging the title panes around. That is a nice ui enhancement. One issue I noticed is if you click the 'detach' arrow and then try to drag the widget left off the screen, it gets 'stuck' to the mouse and after the button is released it still gets 'dragged around. 

This is only happening in IE 10 to my knowledge, and isn't really that big of a deal as I'm not sure many people will try to drag widgets out of the window.

**Comment by tmcgee** [comment]
@roemhildtg Thanks for reporting this. I can confirm that it is occurring for me in IE 11 as well as IE 10. The odd part is that it appears to work without issue in IE9.

We use `dojo/dnd` (drag and drop) to detect the movement of the window while dragging. I tried debugging this and noticed that the `onMoveStop` is not being triggered so code that should run after the window stops moving does not run. Not sure if this is a bug in dojo/dnd or if I missed something when coding this functionality. I will dig further...

**Comment by tmcgee** [comment]
This was addressed in PR #409

**Comment by kcsgisRham** [comment]
@tmcgee This problem seems to be persisting in IE 10 and 11 on Windows 7, 8 and 10 and also in the new Microsoft Edge. I have added the code from PR#405 to my project and we are still experiencing the same issue. Also, it is happening in the CMV demo site. I have downloaded the develop branch and it is not working.

It works as expected in Firefox and Chrome.

**Comment by tmcgee** [comment]
Hmmm. Thanks for posting this. I see what you mean. This was tested with IE10 and IE11 at the time and worked. Looks like something got borked between then and now.

**Comment by tmcgee** [comment]
@cmv/core-committers and everyone else: Can somebody else take a look at this issue? I've tried a couple of times and did not find a solution. Some fresh eyes would be helpful. Thanks in advance for any and all assistance provided.

**Comment by tmcgee** [comment]
I think I have finally discovered the problem here. Internet Explorer does not like a `delay` greater than zero for the dnd [movable](https://github.com/cmv/cmv-app/blob/master/viewer/js/gis/dijit/FloatingTitlePane.js#L32). Setting the delay to zero or omitting it completely solves the problem but causes a few other minor ones. I am reworking the code based on this discovery...

**Comment by cmccullough2** [comment]
Thank you for catching this issue.  I just created a new issue that is the same as this.  I did not see this post.  I look forward to your update.

**Comment by tmcgee** [comment]
Fixed as part of PR #530
